# Deploy portfolio + Allure report to GitHub Pages
name: Deploy static content to Pages

on:
  workflow_run:
    workflows:
      - Playwright E2E Tests
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    # Only deploy when the Playwright workflow completed successfully
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (
        github.event.workflow_run.event == 'push' ||
        github.event.workflow_run.event == 'workflow_dispatch'
      )

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout portfolio from main
      - name: Checkout portfolio
        uses: actions/checkout@v4
        with:
          ref: main

      # 2. Checkout the latest Allure report from gh-pages
      - name: Checkout Allure report
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: allure-source

      # 3. Copy Allure report into portfolio
      - name: Add Allure report
        run: |
          mkdir -p test-report

          if [ -d "allure-source/allure-history" ]; then
            cp -R allure-source/allure-history/. test-report/
          else
            echo "ERROR: Allure report not found."
            exit 1
          fi

          echo "Files in test-report:"
          ls -la test-report/

          echo "Checking test summary:"

          if [ -f "test-report/test-summary.json" ]; then
            cat test-report/test-summary.json
          else
            echo "ERROR: test-summary.json was not found!"
            exit 1
          fi

      # 4. Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 5. Upload complete site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # 6. Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5